language: r
cache: packages
r_packages:
  - covr
services:
  - postgresql
before_script:
  - psql -c 'create database vimpact_test_db;' -U postgres
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
